### ISSUE TITLE
Airhorn

### ISSUE THREAD

**Issue by plima101** [ABTech/abtt#282]
We need an airhorn position so that a member can play an airhorn sound to all tracker webpages open. The idea is that we can have a communal alarm clock to make sure members are awake. Or just so that we designate one person to play the airhorn at events.

**Comment by agotsis** [comment]
I believe that this is an important feature to implement for the future of this organization. 

Also consider adding a Sunchyne button. Simply changing the sound will make this additional feature easy once the airhorn feature is implemented. It is important to reinforce the conditioned response of all techies to begin to strike immediately upon hearing Sunchyne.

This Sunchyne button will be a valuable alternative to GroupMe texts, since we know that everyone always has tracker open.
