### ISSUE TITLE
Member pages broken

### ISSUE THREAD

**Issue by dlareau** [ABTech/abtt#309]
If I am on admin -> timecards looking at a specific period, and I click on a users name, the page responds with "We're sorry, but something went wrong." (an example url is https://tracker.abtech.org/members/179) 
I'm guessing either users aren't supposed to have pages yet, in which case the hyperlink should probably be removed, or something is broken in getting that page in which case that should be addressed.

**Comment by hatkirby** [comment]
The exec role doesn't have permission to view member pages; only tracker management and up does. I can remove the hyperlink for people without access.

**Comment by timparenti** [comment]
> I'm guessing either users aren't supposed to have pages yet

No, they definitely have pages.  You just can't see them, probably because `can? :show, Member` is evaluating to false for you.  25f46e30b1863b1e1f682ee6cd6ba97bb7fefbc2 gave Exec read-only access to timecards, but this particular underlying page assumed those accessing it would already have full HoT permissions.

Firstly, it should give more of a "permission denied" error than a "something went wrong" error.  Secondly, for the actual permissions problem:
* The link you followed (presumably the one on line 7 of `app/views/timecards/view.html.erb`) should be wrapped in an `<% if can? :show, Member %>`, so that the link only displays to those who can follow it.
* If @rmaratos desires, `can :show, Member` could be added under `if member.is_at_least? :exec` in `app/models/ability.rb`, so that all of Exec would be able to follow the link.

**Comment by rmaratos** [comment]
looks like Kelly just did the first permissions solution which is fine.
