### ISSUE TITLE
Send emails to all roles broken

### ISSUE THREAD

**Issue by mousetrapbot01** [ABTech/abtt#320]
If you assign a new member to that role, the email does not update to that person's email.

**Comment by hatkirby** [comment]
Do you mean that adding a second member to a role that already exists doesn't update the all email, or that changing the member assigned to a role doesn't update the all email?

**Comment by ImFromMousetrap** [comment]
Changing the member assigned to a role

**Comment by hatkirby** [comment]
I'm having difficulty reproducing this on tracker-dev. What else can you tell me about the bug you ran into?

**Comment by ImFromMousetrap** [comment]
I originally had Bridget as FoH but then I took her off the position and
Ryan applied so I accepted his request. When I pressed the button to send
emails to everyone in run position, Bridget's email was there instead of
Ryan's.

I checked it just now and the email was set to the correct one. I'm
guessing that there was a delayed update then?

**Comment by hatkirby** [comment]
Yeah sorry, I can't seem to reproduce this on tracker-dev. I added Bridget as FoH on an event, removed her, applied to the role and accepted it, and immediately her email was gone from the email all roles link.
