### ISSUE TITLE
"Account" and "Category" are misnamed in Finance

### ISSUE THREAD

**Issue by iamdabobo** [ABTech/abtt#88]
Maybe this made sense to someone at one point, but I can't figure out why "FMS," "Equipment," etc. are accounts, and "pcard," "purchase order," etc. are categories.  The former should be "category" (or stay "accounts" if it needs to; i realise there are quite a few references to that), and the latter should be "payment method."

**Comment by hatkirby** [comment]
From what I understand, if we're going to go with a stricter accounting metaphor in the future, FMS and Equipment (etc) should be accounts, because they represent expenses, but that the way they exist in tracker right now does not accurately represent an accounting account because the current accounting metaphor is broken. I also agree re payment method, though. This all ties in to a rewrite of finances which will be discussed more in #151 once more important issues are dealt with.
